### ISSUE TITLE
error charaters in path

### ISSUE THREAD

**Issue by oldgnoah1379** [mipen/ModLib#33]
stack trace:
at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
at System.IO.Directory.InternalCreateDiretoryHelper(String path, Boolean checkHost)
at Modlib.FileDatabase.LoadAllFiles(String moduleName)
at Modlib.FileDatabase.Initialise(String moduleFolderName)

**Comment by mipen** [comment]
What language is your operating system in?

**Comment by oldgnoah1379** [comment]
i'm using EN. But path of game not in steam's folder

**Comment by waynezhao12** [comment]
I have the same issue, system language is EN, and game path is in steam's folder.
